[build]
target = "xtensa-esp32s3-none-elf"

[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --monitor --partition-table=partitions.csv"
#runner    = "probe-rs run --probe 303a:1001:98:A3:16:EB:EE:68 --idf-partition-table=partitions.csv --chip esp32s3"
#runner    = "cargo flash --log=INFO --probe 303a:1001:98:A3:16:EB:EE:68 --idf-partition-table=partitions.csv"
rustflags = [
  # GNU LD
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",

  # LLD
  # "-C", "link-arg=-Tlinkall.x",
  # "-C", "linker=rust-lld",
]


[env]
ESP_LOG = "error"

[unstable]
build-std = ["alloc", "core"]